# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: beffec8d14a86c6c2de68150831c3309b182a64a5429fa7a83552e637bbb5c19d6fcfd274686749787f3f01ce7d46369162a65328b2f426c34e4b9d45247cb54

test:
  secret_key_base: 5874b1e57ae71131d98669bcd58d8e2e032781d72ba712fdc49944a732b0a3edf1d532ba86d5cf2921c554a0c8c17ea01b4ee268860e22bba82a96b187f23384

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
